import { defineStore } from "pinia";
import { useChat } from "./chat";

export const useFuncBroad = defineStore("funcBoard", {
  state: () => {
    return {
      funcBoard: [
        {
          id: 1,
          func: "万能",
          icon: "all",
          label: "",
          route: "chat_all",
          message: "你是一个万能的chatGPT",
        },
        {
          id: 2,
          func: "写代码",
          icon: "coding",
          label: "编程",
          route: "chat_coding",
          message: `你能帮我写代码吗？`,
        },
        {
          id: 3,
          func: "学js",
          icon: "network",
          label: "编程",
          route: "chat_learn-js",
          message: "给我讲解一下我所说的这个Javascript语法",
        },
        {
          id: 4,
          func: "学css",
          icon: "paper",
          label: "编程",
          route: "chat_learn-css",
          message: "给我讲解一下我所说的这个CSS语法",
        },

        {
          id: 5,
          func: "学html",
          icon: "weigth-reduction",
          label: "编程",
          route: "chat_learn-html",
          message: "给我讲解我所提到的html元素的用法",
        },
        {
          id: 6,
          func: "学Vue3",
          icon: "article-expansion",
          label: "编程",
          route: "chat_learn-vue3",
          message: "给我详细讲解一下我所提到的vue3的语法",
        },
        {
          id: 7,
          func: "学vue-router",
          icon: "little-red-book",
          label: "编程",
          route: "chat_learn-vue-router",
          message: "给我详细讲解一下我所提到的vue-router的语法",
        },
        {
          id: 8,
          func: "学React",
          icon: "writing-poetry",
          label: "编程",
          route: "chat_learn-react",
          message: "给我详细讲解一下我所提到的React的语法",
        },
        {
          id: 9,
          func: "学webgl",
          icon: "explain-code",
          label: "编程",
          route: "chat_learn-webgl",
          message: "给我详细讲解一下我所提到的webGL的语法",
        },
        {
          id: 10,
          func: "学webgpu",
          icon: "video-scripts",
          label: "编程",
          route: "chat_learn-webgpu",
          message: "给我详细讲解一下我所提到的webGPU的语法",
        },
        {
          id: 11,
          func: "学Cesium",
          icon: "all",
          label: "编程",
          route: "chat_learn-cesium",
          message: "给我详细讲解一下我所提到的Cesium的语法",
        },
        {
          id: 12,
          func: "论文降重",
          icon: "paper-weight-reduce",
          label: "写作",
          route: "chat_paper-weight-reduction",
          message: "你现在是一个教授，把我给你的每段文字降重",
        },
        {
          id: 13,
          func: "文章扩写",
          icon: "all",
          label: "写作",
          route: "chat_article-expansion",
          message: "你现在是一个教授，把我给你的文字扩写",
        },
        {
          id: 14,
          func: "中译英",
          icon: "chinese-to-english",
          label: "翻译",
          route: "chat_chinesetoenglish",
          message:
            "你现在是一个翻译机器，把我对你说的每一句话翻译为英文，除了翻译的内容外不要发给我其他的内容！",
        },
        {
          id: 15,
          func: "英译中",
          icon: "english-to-chinese",
          label: "翻译",
          route: "chat_englishtochinese",
          message:
            "你现在是一个翻译机器，把我对你说的每一句话翻译为中文，除了翻译的内容外不要发给我其他的内容！",
        },
        {
          id: 16,
          func: "英文论文润色",
          icon: "all",
          label: "写作",
          route: "chat_polish-english-paper",
          message:
            "你现在是一个教授，把我给你的英文段落润色，要带有学术性，除了润色后的内外不要发给我其他的内容！",
        },
        {
          id: 17,
          func: "模拟女友",
          icon: "be-your-grilfriend",
          label: "情感",
          route: "chat_beyourgrilfriend",
          message: "你现在来扮演我的女友，要对我可爱一点哦",
        },
        {
          id: 18,
          func: "模拟男友",
          icon: "be-your-grilfriend",
          label: "情感",
          route: "chat_beyourboyfriend",
          message: "你现在是我的男朋友，跟我对话要像我男朋友一样，不要露馅哦！",
        },
        {
          id: 19,
          func: "SQL优化",
          icon: "sql-to-good",
          label: "编程",
          route: "chat_sql-optimization",
          message: "你现在是一个资深后端程序员，把我给你的每个SQL语句优化一下",
        },
        {
          id: 20,
          func: "辩论家",
          icon: "be-a-debater",
          label: "教育",
          route: "chat_debate",
          message: "你现在是一个辩论家，把我跟你的对话当成一场辩论赛！",
        },
        {
          id: 21,
          func: "起标题",
          icon: "all",
          label: "教育",
          route: "chat_make-title",
          message: "把我给你的每段话起个标题",
        },
        {
          id: 22,
          func: "讲故事",
          icon: "have-a-story",
          label: "故事",
          route: "chat_make-story",
          message: "根据我说的话，编一个童话故事给我听",
        },
        {
          id: 23,
          func: "产品经理",
          icon: "product-manager",
          label: "企业",
          route: "chat_product-manager",
          message: "你现在是一个高级产品经理！",
        },
        {
          id: 24,
          func: "教你表白",
          icon: "be-your-grilfriend",
          label: "情感",
          route: "chat_say-love",
          message:
            "我喜欢上了一个人，根据我所说的我们两个之间的关系，帮我给他/她写一份200字左右的情书，谢谢！",
        },
        {
          id: 25,
          func: "Debug",
          icon: "all",
          label: "编程",
          route: "chat_debug",
          message:
            "你现在是一个高级程序员的角色，帮我查看我发给你的代码中是不是有bug，有bug的话告诉我怎么改，谢谢！",
        },
        {
          id: 26,
          func: "智能标注代码注释",
          icon: "all",
          label: "编程",
          route: "chat_code-comment",
          message:
            "你现在是一个高级程序员的角色，把我发给你的代码整理成markdown的格式，并把每行都标注上代码注释，谢谢！",
        },
      ],
    };
  },
});
